import localFont from "next/font/local";
import { MantineProvider } from "@mantine/core";
import { theme } from '../theme';
import '@mantine/core/styles.css';
import { ModalsProvider } from "@mantine/modals";
import { Notifications } from "@mantine/notifications";
import AppContextProvider from "@/hooks/app-context";
import App from "@/components/app-shell";
import { request } from "@/hooks/use-api";

const oswald = localFont({
  src: "../assets/Oswald-VariableFont_wght.ttf",
  variable: "--font-oswald",
  weight: "100 900",
});

export const metadata = {
  title: "KTDash",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // let user = await request('/session.php', {
  //   method: "GET"
  // });

  // console.log(user);

  // if (!user.userid) {
  //   user = undefined
  // }
  return (
    <html lang="en">
      <body className={`${oswald.className}`}>
        <MantineProvider defaultColorScheme="dark" theme={theme}>
          <AppContextProvider>
            <Notifications />
            <ModalsProvider>
              <App>{children}</App>
            </ModalsProvider>
          </AppContextProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
